site_name: Luapower UnQLite
site_url: http://luapower-unqlite.readthedocs.org/
repo_url: https://github.com/coronium-io/luapower-unqlite/
pages:
  - Luapower UnQLite Docs: index.md
  - UnQLite Lua API: api.md
  - About: about.md
